---
title: "Accuracy metrics for individual bee floral resources species"
editor: visual
execute:
  echo: false
---

```{r}
#| message: false
#| results: false
#| warning: false

library(tidyverse)
library(DT)
library(rstatix)
library(ggsignif)
source("R/plot_standards.R")

```

These are the individual accuracy metrics for bee floral resources species in each state.

```{r}
plot_persp <- read.csv("data/results/per-sp-accuracy.csv") %>%
  pivot_wider(names_from = metric, values_from = value) %>% 
  filter(subset == "floralres" & model=="db" & band == "band-1")

floralsp_pa <- plot_persp %>% 
  filter(state == "pa") %>%
  dplyr::select(-model, -subset, -band, -state) %>%
  relocate(support, .before = species_top1) %>%
  distinct() %>% arrange(desc(support))

floralsp_ny <- plot_persp %>% 
  filter(state == "ny") %>%
  dplyr::select(-model, -subset, -band, -state) %>%
  relocate(support, .before = species_top1) %>%
  distinct() %>% arrange(desc(support))

```

## Accuracy metrics of floral resource species

### Pennsylvania species

```{r}

DT::datatable(floralsp_pa %>% 
                mutate(across(species_top1:zero_one_accuracy, \(x) round(x, 2))))

```

### New York Species

```{r}

DT::datatable(floralsp_ny %>% 
                mutate(across(species_top1:zero_one_accuracy, \(x) round(x, 2))))

```


