project:
  type: website
  output-dir: docs

website:
  title: "Deepflora results"
  sidebar:
    contents:
      - section: "Cross validation metrics"
        contents:
          - href: 1_accuracy_unif.qmd
            text: Uniform train-test
          - href: 1.2_accuracy_spatcv.qmd
            text: Spatial cross validation
          - href: 1.2_sp_list.qmd
            text: Species lists
      - section: "Phenology"
        contents:
          - href: 2_examine_phenology.qmd
            text: Phenology mixture models

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
