project:
  type: website
  output-dir: docs

website:
  title: "Deepflora"
  sidebar:
    search: false
    contents:
      - href: index.qmd
        text: Overview
      - section: "Applying Deepbiosphere"
        contents:
          - href: 1.1_accuracy_unif.qmd
            text: "Accuracy: uniform train-test"
          - href: 1.1.1_sp_list.qmd
            text: Individual species accuracy
          - href: 1.2_accuracy_spatcv.qmd
            text: "Accuracy: spatial cross validation"
      - section: "Modeling bloom phenology"
        contents:
          - href: 2.0_Phenology_sp_list.qmd
            text: Top 100 floral resource species
          - href: 2.1_examine_phenology.qmd
            text: Phenology mixture models
          - href: 2.2_examine_phenology_thin.qmd
            text: Phenology mixture models (with thinning)
      - section: "Applying Deepflora workflow"
        contents:
          - href: 3_curvemaps.qmd
            text: Cercis canadensis example
      - section: "Rare plants"
        contents:
          - href: 4_rareplants.qmd
            text: Maps and growing degree days

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
