name: deepflora_r
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - setuptools=65
  - r-base=4.3
  - r-reticulate
  - rpy2
  - r-gam
  - gcc_linux-64
  - gxx_linux-64
  - libstdcxx-ng
  - r-biomod2
  - r-dismo
  - r-randomforest
  - r-rgeos
  - r-pryr
  - r-usethis
  - r-iterators
  - r-devtools
  - r-rjava
  - r-raster
  - r-progress
  - r-foreach
  - r-doparallel
  - r-sp
  - r-optparse
  - r-filelock
  - r-plyr
  - r-here
  - pip:
    - -r requirements.txt
