name: deepflora_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - setuptools=65
  - r-base=4.3
  - r-reticulate
  - rpy2
  - gcc_linux-64
  - gxx_linux-64
  - libstdcxx-ng
  - pip:
    - -r requirements.txt
